<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\HotelSaaS.Infrastructure\HotelSaaS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\backend\HotelSaaS.Domain\HotelSaaS.Domain.csproj" />
    <ProjectReference Include="..\..\backend\HotelSaaS.Application\HotelSaaS.Application.csproj" />
  </ItemGroup>
</Project>
